- name: Deploy App
  hosts: app
  tasks:
    - name: Fetch the latest version off application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted


