all:
  children:
      app:
        hosts:
          appserver:
            ansible_host: 35.241.196.242
      db:
        hosts:
          dbserver:
            ansible_host: 35.233.21.217
            
            

            
