all:
  children:
      app:
        hosts:
          appserver:
            ansible_host: 35.205.119.119
      db:
        hosts:
          dbserver:
            ansible_host: 35.240.68.104

            
