---
- name: install bundler&ruby
  hosts: all
  tags: app-tag
  become: true
  vars:
    packages:
      - ruby-full
      - ruby-bundler
      - build-essential
  tasks:
    - name: install bundler&ruby by apt
      apt:
        name: "{{ packages }}"
        update_cache: yes
